### PR TITLE
Challenge51: Misconfiguration of docker secret in code

### LINKED ISSUE #811: Add misconfiguration of docker secret in code (See for docker compose: https://docs.docker.com/engine/swarm/secrets/)
Create a challenge for docker compose setup, where the compose secret is hardcoded inside teh docker compose yml

TODO:
- [x] Implement a docker-compose setup for wrongsecrets with the secret as an env var, add the compose file to the repo
- [x] implement the challenge according to contributing.md, but make sure we read the challenge from the file so we can play the challenge without the need to actually use teh docker-compose setup.

### PR DESCRIPTION
**Pull request by Shubham-Patel07**
### What kind of changes does this PR include?

-   [ ] Fixes or refactors
-   [x] A new challenge
-   [ ] Additional documentation
-   [ ] Something else

#### Description
New challenge created for misconfiguration of docker secret in code.

### Relations

Closes #811 

### Checklist:

-   [x] All the contributions made are solely the work of me and my co-authors
-   [x] I tested the changes in this PR (if applicable)
-   [x] I added unit tests to ensure my change works (when change in Java or on front-end code)
-   [ ] I added UI tests to ensure my UI changes work (when change in the overall UI, not needed if just adding a challenge)
-   [x] The PR passes pre-commit hooks and automated tests

### CODE REVIEW

**Comment by Shubham-Patel07** [comment]
Hi @commjoen sir, 
Is there anything else expected here in this pull request?

**Comment by commjoen** [comment]
No sir, we might need to relocate the example files, but otherwise we are good ;-)

**Comment by Shubham-Patel07** [comment]
Done !!

**Review by commjoen — APPROVED** [review]
I really like the challenge! I did some small fixes and textual changes, and now it looks awesome! @bendehaan what is your take on it?

Note: we only need to update the docker-compose reference in the text after merge to master ;-)

**Pull request merged**
