### PR TITLE
chore: add Spotless formatter

### PR DESCRIPTION
**Pull request by nbaars**
The configuration will format Java and Markdown and pom files. Java coding standard adheres to the Google Java formatter.

**NOTE** : the build will fail due to the fact that the code does not comply with the coding standards. Once we agree on the configuration you can invoke: `mvn spotless:apply` to format all the code. Should be done when there are no open PRs 😄 

### What kind of changes does this PR include?

-   [x] Fixes or refactors
-   [ ] A new challenge
-   [ ] Additional documentation
-   [ ] Something else

### CODE REVIEW

**Comment by commjoen** [comment]
Thank you! Hope to test & review it soon :-)

**Comment by commjoen** [comment]
Let's revisit this sone when https://github.com/OWASP/wrongsecrets/pull/757 is merged in .

**Review by commjoen — CHANGES_REQUESTED** [review]
Agreeing with @bendehaan here: can we make the markdown stuff managed/beautified by terraform docs?

And it looks like the linting is broken by spotless as well: https://github.com/OWASP/wrongsecrets/actions/runs/4850844405/jobs/8644126106?pr=790 .. not sure if this will help.. Would it maybe be an idea to make sure spotless and linting do the same thing and then apply via ci-lite?

**Comment by nbaars** [comment]
> Is it possible to exclude markdown files? This will clash with prettier formatting / automatically generated terraform docs

I've removed the commit with the formatting of the markdown files

**Review by bendehaan — APPROVED** [review]

**Comment by commjoen** [comment]
Can you please have a look at https://github.com/OWASP/wrongsecrets/actions/runs/5010192603/jobs/8979840704?pr=790 :-)?

**Review by commjoen — APPROVED** [review]

**Review by commjoen — APPROVED** [review]

**Review by commjoen — APPROVED** [review]

**Comment by nbaars** [comment]
> Can you please have a look at https://github.com/OWASP/wrongsecrets/actions/runs/5010192603/jobs/8979840704?pr=790 :-)?

Fixed, this was just a Checkstyle error not sure how it passed on the other branch?

**Pull request merged**
