### PR TITLE
Replace tfsec with trivy on github workflows and renovate.json

### LINKED ISSUE #1764: Migrate tfsec to trivy
### What is the actual behavior?

Tfsec warns that it is no longer updated but lives on as part of Trivy.

### Any possible solutions?

Migrate to [trivy](https://github.com/aquasecurity/trivy) using the [migration guide](https://github.com/aquasecurity/tfsec/blob/master/tfsec-to-trivy-migration-guide.md)

### If the bug is confirmed, would you be willing to submit a PR?

Yes

### PR DESCRIPTION
**Pull request by za**
Issue: https://github.com/OWASP/wrongsecrets/issues/1764

 

### What kind of changes does this PR include?

-   [x] Fixes or refactors
-   [ ] A new challenge
-   [ ] Additional documentation
-   [ ] Something else

#### Description

Update to trivy because tfsec is no longer updated

### Relations

Closes #1764 

### Checklist:

-   [x] All the contributions made are solely the work of me and my co-authors
-   [ ] I tested the changes in this PR (if applicable)
-   [ ] I added unit tests to ensure my change works (when change in Java or on front-end code)
-   [ ] I added UI tests to ensure my UI changes work (when change in the overall UI, not needed if just adding a challenge)
-   [x] The PR passes pre-commit hooks and automated tests

### CODE REVIEW

**Comment by za** [comment]
> Hi @commjoen it's almost midnight here ;) How do I set `TRIVY_VERSION` hence I am not the maintainer of this repo?

Wait, now I see `TRIVY_VERSION` in the `pre-commit.yml` file @commjoen I'm making the changes now...

**Comment by za** [comment]
Hi @commjoen now all checks have passed 🎉 Can you review the PR?

**Comment by za** [comment]
> Thank you for your PR sir! Hope to have a look next week,

Thanks sir @commjoen !

**Review by commjoen — APPROVED** [review]
Lgtm! Thank you @za !

**Comment by za** [comment]
Hi @commjoen I was wondering, how we execute `trivy` in the pre-commit/CI-CD pipeline? As I can see in these changes are only download/setup trivy.

**Comment by commjoen** [comment]
When you do ‘pre-commit install’ it will install the toolchain and do the checks on change within the scope of your new commit.

**Pull request merged**
