### PR TITLE
bugfix(Slack): fix bug for arm on linux & Feat(#618) detect musl

### LINKED ISSUE #618: Add musl based development support
In order to support basic development in Alpine, we could add alpine/musl detection in order to then spin up the musl binaries
Next, have a docker action that runs all tests in alpine and in windows?

### LINKED ISSUE #665: Challenge 19 and 20 is not working on Apple Silicone M1
### Please describe your environment

At least:

-   Operating System + version (and distro if linux): macOS Ventura with Apple Silicon M1
-   Software versions (Java, Terraform, etc): Docker Desktop 4.16 and 4.17. 

### What is the expected behavior?

1. run `docker run -p 8080:8080 jeroenwillemsen/wrongsecrets:latest-no-vault`
2. open challange 19 or 20
3. Spring application should execute `wrongsecrets-c-linux-arm` for challenge 19 and `wrongsecrets-cplus-linux-arm` for 20. This executable run on M1.

### What is the actual behavior?

In step:
3. Spring application executes `wrongsecrets-c-arm` for challenge 19 and `wrongsecrets-cplus-arm` for 20. This executable don't run on M1.

### Other notes on how to reproduce the issue

On Windows and macOS with x64 CPU is working correctly. 

### Any possible solutions?

Spring application should detect right platform and architecture.

### If the bug is confirmed, would you be willing to submit a PR?

Yes / No _(Help can be provided if you need assistance submitting a PR)_

### PR DESCRIPTION
**Pull request by commjoen**
### What kind of changes does this PR include?

-   [x] Fixes or refactors
-   [ ] A new challenge
-   [ ] Additional documentation
-   [x] Something else

#### Description

This PR fixes what is discussed in chat with @MarcinNowak-codes on linux-arm detection and it fixes musl detection (#618)

### Relations

Closes #618
Closes #665 

### Checklist:

-   [ ] All the contributions made are solely the work of me and my co-authors
-   [x] I tested the changes in this PR (if applicable)
-   [x] I added unit tests to ensure my change works (when change in Java or on front-end code)
-   [x] The PR passes pre-commit hooks and automated tests

### CODE REVIEW

**Review by bendehaan — APPROVED** [review]

**Comment by MarcinNowak-codes** [comment]
Issue #665

**Comment by MarcinNowak-codes** [comment]
On macOS with x64 challenge 19 and 20 working as expected :-)

**Comment by MarcinNowak-codes** [comment]
On macOS with M1 arm64 challange 19 and 20 are working correctly.

**Comment by commjoen** [comment]
Thanks!!! Sorry, merged a little too fast

**Pull request merged**
