### PR TITLE
Issue 613 secret gitignore ssh

### PR DESCRIPTION
**Pull request by za**
### What kind of changes does this PR include?

-   [ ] Fixes or refactors
-   [x] A new challenge
-   [ ] Additional documentation
-   [ ] Something else

### Relations

#613 

### Checklist:

-   [ ] All the contributions made are solely the work of me and my co-authors
-   [ ] I tested the changes in this PR (if applicable)
-   [ ] I added unit tests to ensure my change works (when change in Java or on front-end code)
-   [ ] I added UI tests to ensure my UI changes work (when change in the overall UI, not needed if just adding a challenge)
-   [ ] The PR passes pre-commit hooks and automated tests

### CODE REVIEW

**Comment by commjoen** [comment]
Hello @za ! How are you doing? do you need any help with the challenges to be set up?

**Comment by za** [comment]
Hi @commjoen sorry, was quite busy in real life ;-) 
Can I start by reading this manual? https://github.com/OWASP/wrongsecrets/blob/master/CONTRIBUTING.md#how-to-add-a-challenge

Note: I am not too familiar with Java programming language, so I might need more time.

**Comment by za** [comment]
> Can I start by reading this manual? https://github.com/OWASP/wrongsecrets/blob/master/CONTRIBUTING.md#how-to-add-a-challenge

Sorry, no update so far @bendehaan I'll start reading manual above 😎

**Comment by commjoen** [comment]
Do you have any updates on this pr @za ?

**Comment by commjoen** [comment]
I guess that would be following https://github.com/OWASP/wrongsecrets/blob/master/CONTRIBUTING.md#step-2-adding-the-challenge

**Comment by commjoen** [comment]
If you want to: we can do some collaboration over [OWASP Slack](https://github.com/OWASP/wrongsecrets?tab=readme-ov-file#support)

**Comment by commjoen** [comment]
@za, do you have any update on this or can we close the PR?

**Comment by za** [comment]
Hi @commjoen thanks for ping-ing. I haven't had any significant progress yet so far 😿

**Comment by commjoen** [comment]
Will close the PR for now. Feel free to open a new one when you have the time :-).

**Pull request closed without merging**
