### PR TITLE
#810 challenge 42: Created a settings.xml to connect to an imaginary Nexus repo

### LINKED ISSUE #810: Nexus deployment credentials in settings.xml

### PR DESCRIPTION
**Pull request by divyanshuagarwal-23**
### What kind of changes does this PR include?
-Fixes

#### Description
As per #810 task one was to Create a settings.xml to connect to an imaginary Nexus repo, 
I have created the settings.xml file for the same
and have created a challenge reading the credential

### Relations
closes #810 

### References
issue: https://github.com/OWASP/wrongsecrets/issues/810
took ref from: https://github.com/sonatype/nexus-book-examples/blob/master/maven/settings/settings.xml

### CODE REVIEW

**Comment by commjoen** [comment]
Hi @divyanshuagarwal-23 can you please add the challenge code itself as well? having only the isolated XML will not do a lot without the challenge itself. Please have a look at https://github.com/OWASP/wrongsecrets/blob/master/CONTRIBUTING.md on how to add a challenge .

**Comment by divyanshuagarwal-23** [comment]
Sure, working on it

**Comment by commjoen** [comment]
Can you please refactor your challenge to number 42? 41 has been merged ;-)

**Comment by divyanshuagarwal-23** [comment]
@commjoen done, I have updated the challenge

**Comment by commjoen** [comment]
Closing this in favor of https://github.com/OWASP/wrongsecrets/pull/1046/files . Thank you!

**Pull request closed without merging**
