### PR TITLE
Issue 613 secret gitignore ssh

### PR DESCRIPTION
**Pull request by za**
### What kind of changes does this PR include?

-   [ ] Fixes or refactors
-   [x] A new challenge
-   [ ] Additional documentation
-   [ ] Something else

#### Description

Added new secrets on `.gitignore` and `.ssh`

### Relations

#613 

### Checklist:

-   [ ] All the contributions made are solely the work of me and my co-authors
-   [ ] I tested the changes in this PR (if applicable)
-   [ ] I added unit tests to ensure my change works (when change in Java or on front-end code)
-   [ ] I added UI tests to ensure my UI changes work (when change in the overall UI, not needed if just adding a challenge)
-   [ ] The PR passes pre-commit hooks and automated tests

### CODE REVIEW

**Comment by commjoen** [comment]
CoC warning: please don't "steal" other peoples issues unless you are sure that you can take over that issue.

**Comment by za** [comment]
> CoC warning: please don't "steal" other peoples issues unless you are sure that you can take over that issue.

Noted @commjoen :memo:

**Comment by commjoen** [comment]
All good @za , I understand you had good intentions :). The problem often with many of the "good first issues" is that the people who get it assigned need help and time to finish it :) .

**Comment by commjoen** [comment]
Feel free to pick up any of https://github.com/OWASP/wrongsecrets/issues?q=is%3Aissue+is%3Aopen+no%3Aassignee :)

**Comment by za** [comment]
> All good @za , I understand you had good intentions :). The problem often with many of the "good first issues" is that the people who get it assigned need help and time to finish it :) .
> 

No worries @commjoen

I have no intention to take over/steal/coup d etat someone else's issue 😎. It's just because idle and I don't see any progress yet.

**Pull request closed without merging**
